# Generated by Django 4.2.24 on 2025-09-22 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_studentprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('class_name', models.CharField(blank=True, max_length=50)),
                ('subject1', models.CharField(blank=True, max_length=100)),
                ('subject2', models.CharField(blank=True, max_length=100)),
                ('subject3', models.CharField(blank=True, max_length=100)),
                ('subject4', models.CharField(blank=True, max_length=100)),
                ('subject5', models.CharField(blank=True, max_length=100)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('year', models.CharField(blank=True, max_length=20)),
                ('credits', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
